// ============================================================
// DAX MEASURES — Dashboard 4 : Analyse des Tendances
// Dimension temps : dim_date (date_publication, year, quarter, month, day)
// ============================================================

// ── Annonces YTD (Year-to-Date)
Annonces YTD =
CALCULATE(
    [Total Annonces],
    DATESYTD(dim_date[date_publication])
)

// ── Prix moyen YTD
Prix Moyen YTD =
CALCULATE(
    [Prix Moyen],
    DATESYTD(dim_date[date_publication])
)

// ── Évolution prix YoY (Year-over-Year)
Évolution Prix YoY =
VAR prix_actuel = [Prix Moyen]
VAR prix_n1 =
    CALCULATE([Prix Moyen], DATEADD(dim_date[date_publication], -1, YEAR))
RETURN
    DIVIDE(prix_actuel - prix_n1, prix_n1)

// ── Évolution volume d'annonces YoY
Évolution Volume YoY =
VAR vol_actuel = [Total Annonces]
VAR vol_n1 =
    CALCULATE([Total Annonces], DATEADD(dim_date[date_publication], -1, YEAR))
RETURN
    DIVIDE(vol_actuel - vol_n1, vol_n1)

// ── Moyenne mobile 3 mois (prix)
Prix Moyenne Mobile 3M =
AVERAGEX(
    DATESINPERIOD(
        dim_date[date_publication],
        LASTDATE(dim_date[date_publication]),
        -3,
        MONTH
    ),
    [Prix Moyen]
)

// ── Annonces par trimestre (QTD)
Annonces QTD =
CALCULATE(
    [Total Annonces],
    DATESQTD(dim_date[date_publication])
)

// ── Comparaison N vs N-1 (annonces)
Annonces N1 =
CALCULATE([Total Annonces], DATEADD(dim_date[date_publication], -1, YEAR))

// ── Variation absolue annonces vs N-1
Delta Annonces YoY =
[Total Annonces] - [Annonces N1]

// ── Analyse saisonnière : annonces par mois (label)
// Créer une colonne calculée dans Power Query :
// Mois Label = Date.ToText([date_publication], "MMM yyyy", "fr-MA")
//
// Créer une colonne tri :
// Mois Tri = [year] * 100 + [month]
